# Generated by Django 5.0.2 on 2024-02-29 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_products', to='learning_system_app.user'),
        ),
    ]
